# Generated by Django 4.2.4 on 2023-09-01 10:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('ozet', models.TextField(max_length=300)),
                ('icerik', models.TextField()),
                ('olustuma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gunselleme_tarihi', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='baslik', unique=True)),
            ],
        ),
    ]
