# Generated by Django 4.2.4 on 2023-09-01 12:22

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeapp', '0002_alter_yazi_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazi',
            options={'verbose_name': 'yazi', 'verbose_name_plural': 'Yazılar'},
        ),
        migrations.AddField(
            model_name='yazi',
            name='yazar',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='baslik', unique=True),
        ),
    ]
